
INSERT INTO `proyectopeonzas`.`puntas` (`idPunta`,`nombrePunta`,`tipoPunta`) VALUES ('1','Lapiz','Afilada');
INSERT INTO `proyectopeonzas`.`puntas` (`idPunta`,`nombrePunta`,`tipoPunta`) VALUES ('2','Bola','Redonda');
INSERT INTO `proyectopeonzas`.`puntas` (`idPunta`,`nombrePunta`,`tipoPunta`) VALUES ('3','Pico','Plana');

INSERT INTO `proyectopeonzas`.`peonzas` (`nombrePeonza`,`tamanyo`,`precio`,`imagen`,`material`,`cantidad`,`punta`,`cuerda`,`descripcion`) VALUES ('Pegasus','9,2','10,20','https://raw.githubusercontent.com/AdrianRamiroEscamilla/ProyectoTiendaPeonzas/master/imagenePeonzas/Pegasus.jpg','metal','1','1','12','Peonza elegante, vistosa e impactante, perfecta para coleccionistas');
INSERT INTO `proyectopeonzas`.`peonzas` (`nombrePeonza`,`tamanyo`,`precio`,`imagen`,`material`,`cantidad`,`punta`,`cuerda`,`descripcion`) VALUES ('Carnicera','10,5','12,50','https://raw.githubusercontent.com/AdrianRamiroEscamilla/ProyectoTiendaPeonzas/master/imagenePeonzas/Carnicera.jpg','madera','1','1','10','Con su forma agresiva y punta afilada, machaca a tus contricantes!');
INSERT INTO `proyectopeonzas`.`peonzas` (`nombrePeonza`,`tamanyo`,`precio`,`imagen`,`material`,`cantidad`,`punta`,`cuerda`,`descripcion`) VALUES ('Trompus','8,8','14,10','https://raw.githubusercontent.com/AdrianRamiroEscamilla/ProyectoTiendaPeonzas/master/imagenePeonzas/Trompus.jpg','madera','2','2','15','Fantástica peonza ahuevada para los más peques');
INSERT INTO `proyectopeonzas`.`peonzas` (`nombrePeonza`,`tamanyo`,`precio`,`imagen`,`material`,`cantidad`,`punta`,`cuerda`,`descripcion`) VALUES ('Rapid','8,5','15','https://raw.githubusercontent.com/AdrianRamiroEscamilla/ProyectoTiendaPeonzas/master/imagenePeonzas/Rapid.jpg','plastico','3','2','23','Ágil, veloz e insinuante, la peonza Rapid es la más rápida del mercado, ideal para las competiciones y juegos que requieran gran velocidad.');
INSERT INTO `proyectopeonzas`.`peonzas` (`nombrePeonza`,`tamanyo`,`precio`,`imagen`,`material`,`cantidad`,`punta`,`cuerda`,`descripcion`) VALUES ('Furious','10','18','https://raw.githubusercontent.com/AdrianRamiroEscamilla/ProyectoTiendaPeonzas/master/imagenePeonzas/Furious.jpg','metal','3','3','11','Robusta y siniestra, la peonza Furious está diseñada para soportar las embestidas más agresivas.');
INSERT INTO `proyectopeonzas`.`peonzas` (`nombrePeonza`,`tamanyo`,`precio`,`imagen`,`material`,`cantidad`,`punta`,`cuerda`,`descripcion`) VALUES ('Inferno','9,5','16','https://raw.githubusercontent.com/AdrianRamiroEscamilla/ProyectoTiendaPeonzas/master/imagenePeonzas/Inferno.jpg','madera','2','1','4','Inferno llega desde el mísmisimo infierno para danzar endiabladamente.');